### PR TITLE
optimizations proposed by Perlin, corrections proposed by Gustavson

### PR DESCRIPTION
**Pull request by EricBalingit**
Factored out gradient look up and applied Gustavson's corrections. Minor pre calculation tweaks. Comments and references are in the code, still needs to be cleaned up.

### CODE REVIEW

**Comment by EricBalingit** [comment]
Browsing through some of your old tests it looks like they'll break since I commented out .p array and also permMod12

**Comment by EricBalingit** [comment]
Uncommon Tino's shouldn't hurt anything but it will change the meaning of the tests :)

**Comment by EricBalingit** [comment]
*uncommenting

**Comment by jwagner** [comment]
I ran some quick benchmarks:
```
jonas@fractal:~/dev/products/simplex-noise.js/perf (eric)$ ./benchmark.sh 
init: 470,772 ops/sec ±0%
noise2D: 68,050 ops/sec ±0%
noise3D: 43,226 ops/sec ±0%
noise3D2: 42,645 ops/sec ±1%
noise4D: 26,977 ops/sec ±0%
jonas@fractal:~/dev/products/simplex-noise.js/perf (eric)$ ./benchmark.sh 
init: 460,002 ops/sec ±0%
noise2D: 67,796 ops/sec ±0%
noise3D: 42,799 ops/sec ±0%
noise3D2: 43,305 ops/sec ±0%
noise4D: 26,736 ops/sec ±0%
jonas@fractal:~/dev/products/simplex-noise.js/perf (eric)$ g checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
jonas@fractal:~/dev/products/simplex-noise.js/perf (master)$ ./benchmark.sh 
init: 235,462 ops/sec ±1%
noise2D: 67,309 ops/sec ±0%
noise3D: 42,864 ops/sec ±0%
noise3D2: 42,792 ops/sec ±0%
noise4D: 30,983 ops/sec ±0%
jonas@fractal:~/dev/products/simplex-noise.js/perf (master)$ ./benchmark.sh 
init: 236,003 ops/sec ±1%
noise2D: 67,478 ops/sec ±0%
noise3D: 42,242 ops/sec ±1%
noise3D2: 42,550 ops/sec ±0%
noise4D: 31,334 ops/sec ±0%
```

I'm not convinced that your changes actually make the code run any faster. What results do you get when running the benchmark script?

**Comment by EricBalingit** [comment]
I couldn't produce a test from the git fork, not sure what tools you're using... I haven't gotten into node much either.  I wrote a quick test and I'm convinced that my code is SLOWER!  Not sure if the there's some memoization going on under the hood or what, but apparently gradient lookup optimizes better.  My own tests are showing the original code to be consistently faster in 3D and 4D, 2D is about the same.

**Comment by EricBalingit** [comment]
Wish I understood compiler optimizations more. :D

**Comment by EricBalingit** [comment]
Note thought that I haven't done a visual test (I may have introduced bugs in the conversion)... and the algorithm is slightly different, i.e. gradient padding causes different output, so there's no way to test for equivalency.

One thing I found useful though is using a seeded prng - I used an XORShift generator for that.

**Comment by jwagner** [comment]
You can actually set the seed of the node prng as well I'm doing that + a few other things to set up the benchmarks here:
https://github.com/jwagner/simplex-noise.js/blob/master/perf/benchmark.sh

At the CPU level I assume the LUTs are quite fast because they fit into L1 whereas the conditionals can cause branch mispredictions which are fairly expensive. But I haven't done any low level optimizations in quite a while.

At the node level I'm not sure what's going on but a general observation is that JavaScript jits by their nature need simple code to operate on. If functions get to complex they can get confused and will not work efficiently anymore. But I don't think that's what's happening here. The effects of that are usually more severe.

Anyway given that you arrived with similar results I did I guess the optimizations are not worth it. The corrections for the discontinuities sound like a good idea though. Am I correct that those involve nothing more than changing the 0.6 to 0.5 when calculating the t values?

**Comment by jwagner** [comment]
@EricBalingit can you confirm that '_The corrections for the discontinuities sound like a good idea though. Am I correct that those involve nothing more than changing the 0.6 to 0.5 when calculating the t values_'?

**Comment by EricBalingit** [comment]
Yes as far as I understand from Gustavson's updated paper. See the code at the bottom. The correction is indicated in red.

http://www.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf

**Pull request closed without merging**
