### PR TITLE
Adding Math. to random()

### PR DESCRIPTION
**Pull request by Falling10fruit**
I got an error in the debug console:

`
Uncaught TypeError: random is not a function
    at buildPermutationTable (simplex-noise.js:505:22)
`

### CODE REVIEW

**Comment by jwagner** [comment]
Thanks for the PR @Falling10fruit.

As you can see from the test results, it breaks everything though. Random should be the variable random (coming in as an argument) and _not_ math.random. It's likely that the code triggering the error you posted is passing in an invalid random function into simplex-noise If you share the code to reproduce the error I can help you to pin down the issue.

Before opening future PR please run the tests first. I should probably add a contributing file to the Repo to make this more clear.

**Comment by Falling10fruit** [comment]
Alright never mind I forgot that I wasn't supposed to directly use the createNoise functions.

And now all it does is return zero, should I make an issue?
Codepen
VSCode

**Comment by jwagner** [comment]
From the API Docs
> Coordinates should be finite, bigger than -2^31 and smaller than 2^31.

If you can avoid it, also don't sample at exact integer coordinates.

**Comment by Falling10fruit** [comment]
Alright thanks

**Pull request closed without merging**
